services:
  researchspace:
    build:
      context: .
      dockerfile: ./researchspace.dockerfile
    mem_limit: 4g
    mem_reservation: 4g
    ports:
      - "10214:8080"
    environment:
      PLATFORM_OPTS: >-
        -Dcom.bigdata.rdf.sail.webapp.ConfigParams.propertyFile=./bundle-config/RWStore.properties
        -Dconfig.environment.sparqlEndpoint=http://blazegraph:8080/blazegraph/sparql
        -Dconfig.storage.images.type=nonVersionedFile
        -Dconfig.storage.images.mutable=true
        -Dconfig.storage.tmp.type=nonVersionedFile
        -Dconfig.storage.tmp.mutable=true
        -Dorg.eclipse.jetty.server.Request.maxFormContentSize=104857600
        -DruntimeDirectory=./runtime-data
        -Dorg.researchspace.config.baselocation=/runtime-data/config
        -Dconfig.storage.images.root=./runtime-data/images
        -Dconfig.storage.tmp.root=/tmp-data
        -Dconfig.storage.runtime.type=nonVersionedFile
        -Dconfig.storage.runtime.mutable=true
        -Dlog4j.configurationFile=classpath:org/researchspace/logging/log4j2.xml
        -Dconfig.storage.runtime.root=/custom-app/        
    # uncomment if data should be persistable on host
    #volumes:
    #   - ./rs-customisation/custom-app/:/custom-app/
    #   - ./data/researchspace/data/images/:/images/:rw
    #   - ./data/researchspace/data/tmp/:/tmp-data/:rw
    #   - ./data/researchspace/runtime-data/:/runtime-data/
    depends_on:
      - blazegraph
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  blazegraph:
    build:
      context: .
      dockerfile: ./blazegraph.dockerfile
    mem_limit: 8g
    mem_reservation: 8g
    ports:
      - "10215:8080"
    # uncomment if data should be persistable on host
    #volumes:
    # - ./data/blazegraph/:/blazegraph-data
    logging:
     driver: json-file
     options:
      max-size: "200k"
      max-file: "10"

